generator:
  class: sfPropelGenerator
  param:
    model_class:           Cre8News
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          cre8_news
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        title:             News
        display:           [=title, display_date, is_active]
      filter:  ~
      form:    ~
      edit:
        title:             News
      new:
        title:             News
